#spring:
#  application:
#    name: zuul-api-gateway  
#server:
#  port: 8888    
#eureka:
#  instance:
#    instance-id: zuul-api-gateway
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://192.168.8.248:8761/eureka/
#      enabled: true
#ribbon:
#  eureka:
#    enabled: true
#zuul:
#  routes:
#    service-a:
#      path: /serviceA/** # apigateway/serviceA 로 들어오면 service-a 호출
#      serviceId: service-a
#    service-b:
#      path: /serviceB/** # apigateway/serviceB 로 들어오면 service-b 호출
#      serviceId: service-b